name: Docs

on:
  push:

jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Rye
        uses: eifinger/setup-rye@v4
      - name: Install Dependencies
        run: rye sync --no-lock --features docs
      - name: Build Docs
        run: |-
          source .venv/bin/activate
          make --directory docs/ html
      - if: github.ref == 'refs/heads/main'
        name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs/build/html
          single-commit: true
